CC  = cc
CXX = cc
LINKER = $(CC)

ANSI_CFLAGS  = -ansi
ANSI_CFLAGS += -std=c99
ANSI_CFLAGS += -pedantic
ANSI_CFLAGS += -Wextra

CFLAGS   = -O3 $(ANSI_CFLAGS) #-g
ASFLAGS  = -masm=intel
CXXFLAGS = $(CFLAGS)
FCFLAGS  =
LFLAGS   =
DEFINES  = -D_GNU_SOURCE -DALIGNMENT=64
INCLUDES =
LIBS     =
